# Basic YAML configuration example
app:
  name: MyApplication
  version: 1.0.0
  environment: development

database:
  host: localhost
  port: 5432
  username: admin
  password: secret

server:
  host: 0.0.0.0
  port: 8080
  timeout: 30

logging:
  level: INFO
  file: logs/app.log
  rotate: daily

features:
  cache: true
  metrics: true
  authentication: true